apiVersion: apps/v1
kind: Deployment
metadata:
  name: qfs-deployment
  labels:
    app: qfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qfs
  template:
    metadata:
      labels:
        app: qfs
    spec:
      containers:
      - name: qfs-app
        image: qfs:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: qfs-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: qfs-secrets
              key: redis-url
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qfs-service
spec:
  selector:
    app: qfs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
